catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [

    path('',views.index, name="index"),
    path('books/',views.BookListView.as_view(), name="booklist"),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name="bookdetail"),
    path('books/authors/',views.AuthorListView.as_view(),name="authors"),
    path('books/<int:pk>/author/',views.AuthorDeatailView.as_view(),name="authorDetail"),
    path('books/borrowedbooks/',views.LoanedBooksByUser.as_view(), name="loanedbooks"),
    path('books/allborrowedbooks/',views.LoanedBooksByAll.as_view(), name="allloanedbooks"),
    path('books/<uuid:pk>/renewal/',views.renew_books, name="renew_book_librarian"),
    path('books/authorcreate/',views.AuthorCreateView.as_view(), name="authorcreate"),
    path('books/<int:pk>/authorupdate/',views.AuthorUpdateView.as_view(),name="authorupdate"),
    path('books/<int:pk>/authordelete/',views.AuthorDeleteView.as_view(), name="authordelete"),
    path('books/add/',views.BookCreateView.as_view(),name="bookcreate"),
    path('books/<int:pk>/bookupp/',views.BookUpdateView.as_view(), name="bookupdate"),
    path('books/<int:pk>/bookdelete/',views.BookDeleteView.as_view(),name="bookdelete"),
    path('register/',views.register, name="Userregister"),
    path('profile/<int:pk>/',views.UserProfile.as_view(),name="profile"),
    path('book/<uuid:pk>/return/',views.LoanBookReturn.as_view(),name="ReturnBook"),
    path('books/available/',views.MakeBooksAvailable.as_view(),name="makeavailable"),
    path('books/<uuid:pk>/available/',views.MakeBooksAvailable.as_view(),name="makeavailable1"),
    path('books/<uuid:pk>/request/',views.RequestBook.as_view(),name="requestbook"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
# Create your models here.


class Genre(models.Model):
    """table for represting the genre of the book"""

    name = models.CharField(max_length=200, help_text="Enter a book genre (eg: Science Fiction)")

    def __str__(self):

        """for representation of the model"""
        return self.name

class Book(models.Model):
    """table for book representation"""

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,help_text="13 character unique number")
    genre = models.ManyToManyField(Genre, help_text="Select the genre of the book")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"

    def get_count(self):
        return BookInstance.objects.filter(book=self.id).count()

    def __str__(self):
        """for representation of the table"""
        return self.title

class BookInstance(models.Model):
    """table for book-instance representation"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID of the book")
    book = models.ForeignKey('Book',on_delete=models.CASCADE, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (('m','Maintenance'),('o','On Loan'),('a','Available'),('r', 'Received'),('R','Request'),('A','AdvanceRequest'))
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True,default='m', help_text="Book Availability")
    borrower = models.ForeignKey(User,on_delete=models.SET_NULL, null=True,blank=True)

    class Meta:
        ordering = ['due_back']
        permissions = (('Can_mark_retuned','Set book as returned'),)

    @property
    def is_overdure(self):
        if self.due_back and date.today() > self.due_back:
            return True
        else:
            return False
    def __str__(self):
        """for representation of the model"""
        return f"{self.id} {self.book.title}"

class Author(models.Model):
    """table for author representation"""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died',null=True, blank=True)

    class Meta:
        ordering = ['last_name','first_name']
    def __str__(self):
        """for representation of the model"""
        return f"{self.first_name}-{self.last_name}"

class Language(models.Model):
    """table for Language representation"""

    name = models.CharField(max_length=50, help_text="Language (eg: English, German)")

    def __str__(self):
        """for representation of the model"""
        return self.name

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RenewLoanBook(forms.Form):
    renewal_date = forms.DateField(help_text="Enter the date between now and 4 week (default: 3).")
    def clean_renewal_date(self):

        data = self.cleaned_data['renewal_date']

        #To check the entered renewal_date is lessthan current date, if so then raise an approriate error.
        if data < datetime.date.today():
            raise ValidationError(_("Renewal date is in Past."))

        #To check the entered renewal_date is not more than 4 weeks ahead, if so then raise an approriate error
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - as date is more than 4 weeeks ahead."))
        return data

class UserRegister(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name','username','email','password1','password2']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']

class UserProfileDetails(forms.Form):
    firstname = forms.CharField()
    lastname = forms.CharField()

    def save(self):
        super.save(self)

catalog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from catalog.models import Book,BookInstance,Author,Language,Genre
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from django.db.models import Sum
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import RenewLoanBook,UserRegister,UserProfileForm,UserProfileDetails
from django.urls import reverse_lazy
from django.contrib.auth.models import User
import datetime
from django.contrib import messages
# Create your views here.
@login_required
def index(request):
    """View function for home page, showing the overview of the library."""
    num_books = Book.objects.all().count()
    num_book_insta = BookInstance.objects.all().count()
    num_insta_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Author.objects.all().count()

    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1

    ctx = {
       'totalBooks': num_books,
       'totalBookIns': num_book_insta,
       'totalBookAva': num_insta_available,
       'totalAuthor': num_authors,
       'num_visits': num_visits,
    }

    return render(request,'catalog/index.html',ctx)

def register(request):
    if request.method == "POST":
        data = UserRegister(request.POST)
        if data.is_valid():
            data.save()
            messages.success(request,f"You account is successfully created.")
            return redirect(reverse_lazy('login'))
        else:
            ctx = {'form': data}
            return render(request,'catalog/register.html',ctx)
    else:
        userdata = UserRegister()
    ctx = {
       'form': userdata,
    }
    return render(request,'catalog/register.html',ctx)


class BookListView(ListView):
    model = Book
    context_object_name = 'booklist'
    template_name = 'catalog/list.html'

class BookDetailView(LoginRequiredMixin,DetailView):
    model = Book

    def get(sef,request,pk):
        book = Book.objects.get(id=pk)
        bookins = BookInstance.objects.filter(book=pk)
        bookcount = BookInstance.objects.filter(book=pk).count()
        bookcountAva = BookInstance.objects.filter(book=pk).filter(status__exact="a").count()
        if bookcountAva > 0:
            diffbooks = bookcountAva
            requestBook = BookInstance.objects.filter(book=pk).filter(status__exact="a").first()
            proposed_date = datetime.date.today() + datetime.timedelta(weeks=3)
            form = RenewLoanBook(initial={'renewal_date':proposed_date})
            ctx = {'book':book,'instances':bookins,'availablebooks':diffbooks,
                   'requestbook':requestBook,'form':form}
            return render(request,'catalog/detail.html',ctx)
        ctx = {'book':book,'instances':bookins}
        return render(request,'catalog/detail.html',ctx)
class AuthorListView(ListView):
    model = Author
    paginate_by = 2
    template_name = "catalog/author.html"
    def get(self,request):
        authors = Author.objects.all()
        ctx = {'authors': authors}
        return render(request,self.template_name,ctx)

class AuthorDeatailView(LoginRequiredMixin,DetailView):
    model = Author
    template_name = 'catalog/authordetail.html'
    def get(self,request,pk):
        author = Author.objects.get(id=pk)
        books = Book.objects.filter(author=author.id)
        ctx = {'author': author,'books':books}
        return render(request,self.template_name,ctx)

class LoanedBooksByUser(LoginRequiredMixin,ListView):
    model = BookInstance
    paginate_by = 8
    template_name = 'catalog/loanedBooksByUser.html'
    def get(self,request):
        loaned = BookInstance.objects.filter(borrower=self.request.user).filter(status__exact="o").order_by('-due_back')
        ctx = {'loanBooks':loaned}
        return render(request,self.template_name,ctx)

class LoanedBooksByAll(LoginRequiredMixin,ListView):
    model = BookInstance
    template_name = 'catalog/loanedBooksByUser.html'
    def get(self,request):
        loaned = BookInstance.objects.filter(status__exact="o").order_by('-due_back')
        ctx = {'loanBooks':loaned}
        return render(request,self.template_name,ctx)

@permission_required('catalog.Can_mark_retuned')
def renew_books(request,pk):

    book_instance = get_object_or_404(BookInstance,id=pk)
    if request.method == "POST":
        form = RenewLoanBook(request.POST)
        print(form)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return redirect(reverse_lazy('catalog:allloanedbooks'))
    else:
        proposed_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewLoanBook(initial={'renewal_date':proposed_date})
    ctx = {
       'book_instance':book_instance,
       'form': form
    }

    return render(request,'catalog/renewal_book.html',ctx)

class AuthorCreateView(LoginRequiredMixin,CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '12/12/9999'}
    template_name = 'catalog/author_form.html'
    success_url = reverse_lazy('catalog:authors')

class AuthorUpdateView(LoginRequiredMixin,UpdateView):
    model = Author
    fields = '__all__'
    template_name = 'catalog/author_form.html'
    success_url = reverse_lazy('catalog:authors')

class AuthorDeleteView(LoginRequiredMixin,DeleteView):
    model = Author
    success_url = reverse_lazy('catalog:authors')
    template_name = 'catalog/author_confirm_delete.html'

class BookCreateView(LoginRequiredMixin,CreateView):
    model = Book
    fields = '__all__'
    template_name = 'catalog/book_form.html'
    success_url = reverse_lazy('catalog:booklist')

class BookUpdateView(LoginRequiredMixin,UpdateView):
    model = Book
    fields = ['author','summary','genre']
    template_name = 'catalog/book_form.html'
    success_url = reverse_lazy('catalog:booklist')

class BookDeleteView(LoginRequiredMixin,DeleteView):
    model = Book
    template_name = 'catalog/book_confirm_delete.html'
    success_url = reverse_lazy('catalog:booklist')

class UserProfile(UpdateView):
    model = User
    def get(self,request,pk):
        user = UserProfileForm(instance=request.user)
        ctx = {'form':user}
        return render(request,'catalog/profile.html',ctx)
    def post(self,request,pk):
        user = get_object_or_404(User,id=pk)

class LoanBookReturn(LoginRequiredMixin,ListView):

    model = BookInstance
    template_name = 'catalog/loanedBooksByUser.html'
    def get(self,request,pk):
        book = BookInstance.objects.get(id=pk)
        book.status = 'r'
        book.save()
        loaned = BookInstance.objects.filter(borrower=self.request.user).filter(status__exact="o").order_by('-due_back')
        ctx = {'loanBooks':loaned}
        return render(request,self.template_name,ctx)

class MakeBooksAvailable(LoginRequiredMixin,ListView):

    def get(self,request,**kwargs):
        if (kwargs):
            bookstatus = BookInstance.objects.get(id=kwargs['pk'])
            if bookstatus.status == 'r':
                bookstatus.status = 'a'
                bookstatus.due_back = None
                bookstatus.borrower = None
                bookstatus.save()
            if bookstatus.status == 'R':
                bookstatus.status = 'o'
                bookstatus.due_back = datetime.date.today()+datetime.timedelta(weeks=3)
                bookstatus.save()
        loanBooks = BookInstance.objects.filter(status__exact="r").order_by('-due_back')
        requestb = BookInstance.objects.filter(status__exact="R").order_by('-due_back')
        ctx = {'loanBooks':loanBooks,
                'requestb':requestb}
        return render(request,'catalog/returnbook.html',ctx)

class RequestAdvanceBook(LoginRequiredMixin,ListView):
    model = BookInstance
    def get(self,request,pk):
        booksave = BookInstance.objects.get(id=pk)
        booksave.status = 'A'
        booksave.save()
        book = Book.objects.get(id=pk)
        bookins = BookInstance.objects.filter(book=pk)
        bookcount = BookInstance.objects.filter(book=pk).count()
        bookcountAva = BookInstance.objects.filter(book=pk).filter(status__exact="a").count()
        if bookcountAva > 0:
            diffbooks = bookcountAva
            ctx = {'book':book,'instances':bookins,'availablebooks':diffbooks}
            return render(request,'catalog/detail.html',ctx)
        ctx = {'book':book,'instances':bookins}
        return render(request,'catalog/detail.html',ctx)

class RequestBook(LoginRequiredMixin,ListView):
    model = BookInstance
    def get(self,request,pk):
        bookstatus = BookInstance.objects.get(id=pk)
        bookstatus.status = 'R'
        bookstatus.borrower = request.user
        bookstatus.save()
        return redirect(reverse_lazy('catalog:bookdetail',kwargs={'pk':bookstatus.book.id}))

catalog/templates/catalog/author.html
{% extends "catalog/base.html" %}
{% block title %}
<title>Authors Page</title>
{% endblock %}
{% block content %}
    <h2>List of all Authors</h2>
    <hr>
    {% for author in authors %}
     <ul class="author">
       <a href="{% url "catalog:authorDetail" author.id %}"><li>{{ author.first_name }} - {{ author.last_name }}</li></a>
       <hr>
     </ul>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
<title>Author Create</title>
{% endblock %}
{% block content %}
   {% if author.id %}
     <h2>Author Update Form </h2>
   {% else %}
     <h2>Author Create Form</h2>
   {% endif %}
   <hr>
   <form class="" action="" method="post">
     {% csrf_token %}
     {{ form | crispy }}
     <hr>
     {% if author.id %}
        <input type="submit" name="Update" value="Update" class="btn btn-outline-success">
        <input type="submit" name="Cancel" value="Cancel" class="btn btn-outline-danger" onclick="window.location='{% url 'catalog:authorDetail' author.id %}';return false;">
     {% else %}
        <input type="submit" name="Create" value="Create" class="btn btn-outline-success">
        <input type="submit" name="Cancel" value="Cancel" class="btn btn-outline-danger" onclick="window.location='{% url 'catalog:authorcreate' %}';return false;">
     {% endif %}

   </form>
{% endblock %}

catalog/templates/catalog/authordetail.html
{% extends "catalog/base.html" %}
{% block title %}
  <title>About Author</title>
{% endblock %}
{% block content %}
  <h2>About Author: <em>{{ author.first_name }} {{ author.last_name }}</em></h2>
  <p><strong>DOB: </strong> {{ author.date_of_birth}}</p>
  <p><strong>DOD: </strong> {{ author.date_of_death }}</p>
  {% if user.is_staff %}
     <a href="{% url 'catalog:authorupdate' author.id %}"><input type="submit" name="Update" value="Update" class="btn btn-outline-info"></a>
     <a href="{% url 'catalog:authordelete' author.id %}"><input type="submit" name="Delete" value="Delete" class="btn btn-outline-danger"></a>
  {% endif %}
  <hr>
  <hr>
  <h2>Books by the Author:</h2>
  {% for book in books %}
   <p><strong>Title: </strong>{{ book.title }}</p>
   <p><strong>Summary: </strong>{{ book.summary }}</p>
   <p><strong>Copies: </strong>{{ book.get_count }}</p>
   <p><strong>ISBN: </strong>{{ book.isbn }}</p>
   <hr>
  {% endfor %}
{% endblock %}

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block style %}
    {% endblock %}
    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>
     <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
       <a class="navbar-brand" href="#" style="border-radius: 5px;">Library</a>
       <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarcollapse" name="button">
           <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarcollapse">
          <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'catalog:index' %}">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'catalog:booklist' %}">All Books</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'catalog:authors' %}">All Authors</a>
              </li>
          </ul>
        </div>
     </nav>
     <div class="row">
       <div class="col-2">
             <ul class="nav logio">
               {% if user.is_authenticated %}
                  {% if user.is_staff %}
                     <li class="nav-item"><a class="nav-link" href="{% url 'catalog:allloanedbooks' %}">AllBorrowedBooks</a></li>
                     <li class="nav-item"><a class="nav-link" href="{% url 'catalog:bookcreate' %}">Add Book</a></li
                     <li class="nav-item"><a class="nav-link" href="{% url 'catalog:authorcreate' %}">Add Author</a></li>
                     <li class="nav-item"><a class="nav-link" href="{% url 'catalog:makeavailable' %}">Inbox</a></li>
                  {% else %}
                     <li class="nav-item"><a class="nav-link" href="{% url 'catalog:loanedbooks' %}">BorrowedBooks</a></li>
                  {% endif %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'catalog:profile' user.id %}">Profile</li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'password_change' %}">Change Password</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
               {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
               {% endif %}
             </ul>
       </div>
       <div class="col-9">
         {% if messages %}
            {% for message in messages %}4
                <h3 class="text_success">{{ message }}</h3>
            {% endfor %}
         {% endif %}
         <div class="container">
           {% block content %}
           {% endblock %}
         </div>
         <div style="background-color: white;">
         <h3>About the Application.</h3>
         <ul>
           <li>User need to register first inorder to access the books.</li>
           <li>User can take as many book as they want.</li>
           <li>Once the books is borrowed, the return period will <strong>3 weeks</strong> from the date of book borrowed.</li>
           <li>In order to get the book, user must request for the book, based on the availability which is shown in the book
               detail page.</li>
           <li>Once the request is done, the librarian can aprrove the book. After the approval, the book is loaned to the requested user,
               same can be seen in the user, Borrowed book page.</li>
         </ul>
         <hr>
         <h4>Future Updates,</h4>
       </div>
       </div>
      </div>
  </body>
</html>

catalog/templates/catalog/detail.html
{% extends "catalog/base.html" %}
{% block title %}
    <title>Detail Page</title>
{% endblock %}
{% block content %}
   <h1>Title: {{ book.title }}</h1>
   <hr>
   <p><strong>Author: </strong>{{ book.author }}</p>
   <p><strong>Summary: </strong>{{ book.summary }}</p>
   <p><strong>ISBN: </strong>{{ book.isbn }}</p>
   <p><strong>Genre: </strong>{{ book.display_genre }}</p>
   <p><strong>Language: </strong>{{ book.language }}</p>
   {% if user.is_staff %}
      <a href="{% url 'catalog:bookupdate' book.id %}" class="btn btn-outline-info">Update</a>
      <a href="{% url 'catalog:bookdelete' book.id %}" class="btn btn-outline-danger">Delete</a>
   {% else %}
      {% if availablebooks %}
      <button type="button" name="button" class="btn btn-success">{{ availablebooks }}</button>
      <button type="button" name="button" class="btn btn-success" data-toggle="modal" data-target="#Newmodal">
        Request a Book</button>
      <div class="modal fade" role="dialog" id="Newmodal">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4>Book Request</h4>
              <button type="button" name="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <form class="" action="index.html" method="post">
                {% csrf_token %}
                <label for="#bkname">title: </label>
                <input type="text" name="bkname" id="bkname" class="form-control" value="{{ requestbook.book.title }}">
                <label for="#bkauthor">Author: </label>
                <input type="text" name="bkauthor" id="bkauthor" class="form-control" value="{{ requestbook.book.author }}">
                <label for="#bkid">Unique Id:</label>
                <input type="text" name="bkid" id="bkid" class="form-control" value="{{ requestbook.id }}">
                <label for="#borro">Borrower: </label>
                <input type="text" name="borrowe" id='borro'class="form-control"value="{{ request.user.username }}">
                <div class="modal-footer">
                  <button type="button" name="button" class="btn btn-success">
                    <a href="{% url 'catalog:requestbook' requestbook.id %}" style="text-decoration:none;color:white;">Submit</a>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>

      </div>
      {% else %}
        <div class="jumbotron" style="height: 200px;">
         <h4>No copies are available at the moment.</h4>
         <p>Wanna register for the Queue to get the book?</p>
         <button type="button" name="button" data-toggle="modal" data-target="#Mymodal" class="btn btn-success">Advance Regn</button>
         <div class="modal fade" id="Mymodal" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4>Advance Book Register Form</h4>
                <button type="button" name="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <form class="" action="" method="post">
                  {% csrf_token %}
                  <label for="Bookname">Book:</label>
                  <input type="text" value="{{ book.title }}" class="form-control" id="Bookname">
                  <label for="Bookauthor">Author:</label>
                  <input type="text" value="{{ book.author }}" class="form-control" id="Bookauthor">
                  <label for="Bookisbn">ISBN:</label>
                  <input type="text" value="{{ book.isbn }}" class="form-control" id="Bookisbn">
                  <label for="name">Borrower: </label>
                  <input type="text" value="{{ user.username }}" class="form-control" id="name">
                  <div class="modal-footer">
                    <button type="submit" name="button" class="btn btn-success">Submit</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
         </div>
        </div>
      {% endif %}
   {% endif %}
   <hr>
   <hr>
   <div class="">
     <h2>Copies: </h2>
     {% for copy in instances %}
       <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm'%}text-danger
       {% else %}text-warning{% endif %}">
         {{ copy.get_status_display }}
       </p>
       {% if copy.status != 'a '%}
           <p><strong>Due Date: </strong> {{ copy.due_back }}</p>
       {% endif %}
       <p><strong>Imprint: </strong>{{ copy.imprint }}</p>
       <p class="text-muted"><strong>Id: </strong>{{ copy.id }}</p>
       <hr>
     {% endfor %}
   </div>
{% endblock %}

catalog/templates/catalog/loanedBooksByUser.html
{% extends "catalog/base.html" %}
{% block title %}
<title>Loaned Books</title>
{% endblock %}
{% block content %}
  <h3>Loaned Books</h3>
  <hr>
  {% if loanBooks %}
     <ul>
       {% for book in loanBooks %}
        <li class={% if book.is_overdure %}text-danger{% else %}text-success{% endif %}>
          <a href="{% url 'catalog:bookdetail' book.book.id %}">{{ book.book.title }} </a>(<small>due on</small> {{ book.due_back }}) |
             borrowed by {{ book.borrower.username }}
          {% if user.is_staff %}
             <p style="float: right;">
               <a href="{% url 'catalog:renew_book_librarian' book.id %}" style="text-decoration: none;" class="btn btn-outline-info">Renew</a>
             </p>
          {% else %}
            <p style="float: right;" class={% if book.is_overdure %}text-danger{% else %}text-success{% endif %}>
              <a href="{% url 'catalog:ReturnBook' book.id %}" style="text-decoration: none;" class="btn btn-outline-success">Return</a>
            </p>
          {% endif %}
        </li>
        <hr>
       {% endfor %}
     </ul>
  {% else %}
     <h2>You haven't loaned any books yet.</h2>
  {% endif %}
{% endblock %}